services:
  - type: web
    name: 13f-ownership
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python scripts/app.py --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
