#!/usr/bin/env python3
"""Concatenate per-session closed-item files into a single flat log.

Reads every ``docs/closures/*.md`` file (excluding README.md) in
alphabetical order and emits a single Markdown table at
``docs/closed-items-log.md``. The generated file is git-ignored
and rebuildable at any time; do not hand-edit.

Usage
-----
    python3 scripts/concat_closed_log.py

Output
------
    docs/closed-items-log.md
"""
from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
CLOSURES_DIR = REPO_ROOT / "docs" / "closures"
OUTPUT = REPO_ROOT / "docs" / "closed-items-log.md"

HEADER = (
    "# Closed items log (generated)\n\n"
    "Generated by ``scripts/concat_closed_log.py`` from "
    "``docs/closures/*.md``. Do not hand-edit — changes here will be\n"
    "overwritten on next run. New closures go in "
    "``docs/closures/YYYY-MM-DD-<session-name>.md``.\n\n"
    "The historical pre-cutover archive (rows closed before\n"
    "2026-04-23) lives in ``ROADMAP.md § Closed items (log)``.\n\n"
    "| # | Item | Priority | Notes |\n"
    "|---|------|----------|-------|\n"
)


def collect_rows() -> list[str]:
    if not CLOSURES_DIR.is_dir():
        print(f"error: {CLOSURES_DIR} does not exist", file=sys.stderr)
        sys.exit(1)

    rows: list[str] = []
    files = sorted(
        p for p in CLOSURES_DIR.glob("*.md") if p.name != "README.md"
    )
    for path in files:
        for raw in path.read_text().splitlines():
            line = raw.rstrip()
            if not line.startswith("|"):
                continue
            stripped = line.replace("|", "").replace("-", "").replace(" ", "")
            if stripped == "":
                continue
            rows.append(line)
    return rows


def main() -> int:
    rows = collect_rows()
    body = "\n".join(rows)
    OUTPUT.write_text(HEADER + body + ("\n" if body else ""))
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)} ({len(rows)} rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
