"""
Backfill holdings_v2.manager_type using categorized_institutions_funds_v2.csv.

The CSV (5,782 hand-curated rows, 2026-04-05 via commit 87e832b) was
generated by categorizing institutions where manager_type was NULL or
'unknown' with a richer vocabulary than build_managers.py produces:
  active, strategic, wealth_management, pension_insurance,
  endowment_foundation, venture_capital, SWF, hedge_fund, private_equity,
  mixed, quantitative, activist, passive

This script:
1. Reads the CSV.
2. For each named entity, updates holdings_v2 WHERE COALESCE(
   inst_parent_name, manager_name) matches AND manager_type IS NULL or
   'unknown'.
3. Also updates managers.strategy_type / manager_type where applicable.
4. Stamps data_freshness on holdings_v2.

Repointed from the dropped legacy `holdings` table during the
build_managers.py REWRITE Phase 4 (Batch 3 close). The previous target
was Stage-5-dropped and this script was silently broken.

Usage:
    python3 scripts/backfill_manager_types.py               # staging
    python3 scripts/backfill_manager_types.py --production  # prod
    python3 scripts/backfill_manager_types.py --dry-run     # report only
"""
import argparse
import os
import sys
from pathlib import Path

import duckdb
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from db import record_freshness  # noqa: E402

CSV_PATH = Path(__file__).parent.parent / 'categorized_institutions_funds_v2.csv'


def normalize_name(name):
    """Strip whitespace and lowercase for matching."""
    if pd.isna(name) or not name:
        return ''
    return str(name).strip().lower()


def run(db_path, dry_run=False):
    print(f'Opening {db_path}...', flush=True)
    con = duckdb.connect(db_path, read_only=False)

    # Load CSV
    df = pd.read_csv(CSV_PATH)
    df['name_clean'] = df['name'].apply(normalize_name)
    # Drop uncategorized and any rows where category is NaN
    categorized = df[df['category'].notna() & (df['category'] != 'uncategorized')].copy()
    print(f'CSV: {len(df)} total rows, {len(categorized)} categorized '
          f'(non-uncategorized)', flush=True)
    print('Categories:', flush=True)
    print(categorized['category'].value_counts())

    # Before snapshot
    before = con.execute("""
        SELECT
            COUNT(*) as total_rows,
            COUNT(CASE WHEN manager_type IS NULL OR manager_type = 'unknown' THEN 1 END) as unknown_rows,
            COUNT(DISTINCT CASE WHEN manager_type IS NULL OR manager_type = 'unknown'
                                THEN COALESCE(inst_parent_name, manager_name) END) as unknown_entities
        FROM holdings_v2
    """).fetchone()
    print(f'\nBEFORE: total={before[0]:,}, unknown rows={before[1]:,}, '
          f'unknown entities={before[2]:,}',
          flush=True)

    # Create a temp table from the CSV for efficient SQL update
    con.execute("""
        CREATE OR REPLACE TEMP TABLE _manager_categories (
            name_clean VARCHAR,
            category VARCHAR
        )
    """)
    for _, row in categorized.iterrows():
        con.execute(
            "INSERT INTO _manager_categories VALUES (?, ?)",
            [row['name_clean'], row['category']]
        )
    csv_loaded = con.execute("SELECT COUNT(*) FROM _manager_categories").fetchone()[0]
    print(f'Loaded {csv_loaded} category mappings to temp table', flush=True)

    # Projected impact — computed in both dry-run and apply so logs match.
    projected = con.execute("""
        SELECT COUNT(*)
        FROM holdings_v2 h
        JOIN _manager_categories mc
          ON LOWER(TRIM(COALESCE(h.inst_parent_name, h.manager_name))) = mc.name_clean
        WHERE h.manager_type IS NULL OR h.manager_type = 'unknown'
    """).fetchone()[0]
    print(f'Projected holdings_v2 rows to update: {projected:,}', flush=True)

    if dry_run:
        managers_projected = con.execute("""
            SELECT COUNT(*)
            FROM managers m
            JOIN _manager_categories mc
              ON LOWER(TRIM(COALESCE(m.parent_name, m.manager_name))) = mc.name_clean
            WHERE m.strategy_type IS NULL OR m.strategy_type = 'unknown'
        """).fetchone()[0]
        print(f'Projected managers rows to update: {managers_projected:,}', flush=True)

        # Sample: top 10 entities by row count that would flip
        sample = con.execute("""
            SELECT
                COALESCE(h.inst_parent_name, h.manager_name) AS entity,
                MIN(h.cik) AS sample_cik,
                mc.category AS new_type,
                COUNT(*) AS rows
            FROM holdings_v2 h
            JOIN _manager_categories mc
              ON LOWER(TRIM(COALESCE(h.inst_parent_name, h.manager_name))) = mc.name_clean
            WHERE h.manager_type IS NULL OR h.manager_type = 'unknown'
            GROUP BY entity, mc.category
            ORDER BY rows DESC
            LIMIT 10
        """).fetchall()
        if sample:
            print('\nSample (top 10 entities that would flip):', flush=True)
            for entity, cik, new_type, rows in sample:
                print(f'  cik={cik}  {entity[:50]:50s} → {new_type:20s} ({rows:,} rows)', flush=True)

        con.close()
        print('\n[dry-run] no changes applied.', flush=True)
        return

    # Update holdings_v2.manager_type — only where current value is NULL or 'unknown'
    con.execute("""
        UPDATE holdings_v2
        SET manager_type = mc.category
        FROM _manager_categories mc
        WHERE LOWER(TRIM(COALESCE(holdings_v2.inst_parent_name, holdings_v2.manager_name))) = mc.name_clean
          AND (holdings_v2.manager_type IS NULL OR holdings_v2.manager_type = 'unknown')
    """)

    # Also update managers table if it has similar columns
    try:
        con.execute("""
            UPDATE managers
            SET strategy_type = mc.category
            FROM _manager_categories mc
            WHERE LOWER(TRIM(COALESCE(managers.parent_name, managers.manager_name))) = mc.name_clean
              AND (managers.strategy_type IS NULL OR managers.strategy_type = 'unknown')
        """)
        print('Updated managers table', flush=True)
    except Exception as e:
        print(f'(managers table update skipped: {e})', flush=True)

    # After snapshot
    after = con.execute("""
        SELECT
            COUNT(CASE WHEN manager_type IS NULL OR manager_type = 'unknown' THEN 1 END) as unknown_rows,
            COUNT(DISTINCT CASE WHEN manager_type IS NULL OR manager_type = 'unknown'
                                THEN COALESCE(inst_parent_name, manager_name) END) as unknown_entities
        FROM holdings_v2
    """).fetchone()
    print(f'AFTER:  unknown rows={after[0]:,}, unknown entities={after[1]:,}',
          flush=True)
    print(f'Recovered: {before[1] - after[0]:,} rows, '
          f'{before[2] - after[1]:,} entities',
          flush=True)

    # Distribution of new manager types
    print('\nNew manager_type distribution in holdings_v2:', flush=True)
    dist = con.execute("""
        SELECT manager_type, COUNT(*) as rows,
               COUNT(DISTINCT COALESCE(inst_parent_name, manager_name)) as entities
        FROM holdings_v2
        GROUP BY manager_type
        ORDER BY rows DESC
    """).fetchdf()
    print(dist.to_string())

    # Spot-check a few
    print('\nSpot-check a few entities:', flush=True)
    samples = [
        'BATTERY MANAGEMENT CORP.',
        'LILLY ENDOWMENT INC',
        'DEERE & CO',
        'FOUNDRY GROUP, LLC',
    ]
    for s in samples:
        r = con.execute("""
            SELECT COALESCE(inst_parent_name, manager_name) as entity, manager_type
            FROM holdings_v2
            WHERE UPPER(TRIM(COALESCE(inst_parent_name, manager_name))) = ?
            LIMIT 1
        """, [s.upper().strip()]).fetchone()
        if r:
            print(f'  {r[0][:50]:50s} → {r[1]}', flush=True)
        else:
            print(f'  {s} not found in holdings_v2', flush=True)

    try:
        record_freshness(con, "holdings_v2")
    except Exception as e:
        print(f'  [warn] record_freshness(holdings_v2) failed: {e}', flush=True)
    con.execute("CHECKPOINT")
    con.close()
    print('\nDone.', flush=True)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--production', action='store_true',
                        help='Target production DB (default: staging)')
    parser.add_argument('--dry-run', action='store_true',
                        help='Report projected row counts without writing.')
    args = parser.parse_args()

    base = Path(__file__).parent.parent
    if args.production:
        db = base / 'data' / '13f.duckdb'
        print('WARNING: Running against PRODUCTION database', flush=True)
    else:
        db = base / 'data' / '13f_staging.duckdb'
        print('Target: staging database', flush=True)

    if not db.exists():
        print(f'Database not found: {db}', flush=True)
        sys.exit(1)

    run(str(db), dry_run=args.dry_run)


if __name__ == '__main__':
    main()
