"""
Backfill holdings.manager_type using categorized_institutions_funds_v2.csv.

The CSV was generated by categorizing the uncategorized institutions
(where manager_type was NULL or 'unknown') with expanded categories:
  active, strategic, wealth_management, pension_insurance,
  endowment_foundation, venture_capital, SWF, hedge_fund, private_equity,
  mixed, quantitative, activist, passive

This script:
1. Reads the CSV
2. For each named entity, updates holdings WHERE COALESCE(inst_parent_name, manager_name)
   matches AND manager_type IS NULL or 'unknown'
3. Also updates the managers.strategy_type and managers.manager_type where applicable
4. Runs in staging first; --production flag for explicit prod update

Usage:
    python3 scripts/backfill_manager_types.py                # staging
    python3 scripts/backfill_manager_types.py --production   # prod
"""
import argparse
import sys
from pathlib import Path

import duckdb
import pandas as pd

CSV_PATH = Path(__file__).parent.parent / 'categorized_institutions_funds_v2.csv'


def normalize_name(name):
    """Strip whitespace and lowercase for matching."""
    if pd.isna(name) or not name:
        return ''
    return str(name).strip().lower()


def run(db_path):
    print(f'Opening {db_path}...')
    con = duckdb.connect(db_path, read_only=False)

    # Load CSV
    df = pd.read_csv(CSV_PATH)
    df['name_clean'] = df['name'].apply(normalize_name)
    # Drop uncategorized and any rows where category is NaN
    categorized = df[df['category'].notna() & (df['category'] != 'uncategorized')].copy()
    print(f'CSV: {len(df)} total rows, {len(categorized)} categorized (non-uncategorized)')
    print('Categories:')
    print(categorized['category'].value_counts())

    # Before snapshot
    before = con.execute("""
        SELECT
            COUNT(*) as total_rows,
            COUNT(CASE WHEN manager_type IS NULL OR manager_type = 'unknown' THEN 1 END) as unknown_rows,
            COUNT(DISTINCT CASE WHEN manager_type IS NULL OR manager_type = 'unknown'
                                THEN COALESCE(inst_parent_name, manager_name) END) as unknown_entities
        FROM holdings
    """).fetchone()
    print(f'\nBEFORE: total={before[0]:,}, unknown rows={before[1]:,}, unknown entities={before[2]:,}')

    # Create a temp table from the CSV for efficient SQL update
    con.execute("""
        CREATE OR REPLACE TEMP TABLE _manager_categories (
            name_clean VARCHAR,
            category VARCHAR
        )
    """)
    for _, row in categorized.iterrows():
        con.execute(
            "INSERT INTO _manager_categories VALUES (?, ?)",
            [row['name_clean'], row['category']]
        )
    csv_loaded = con.execute("SELECT COUNT(*) FROM _manager_categories").fetchone()[0]
    print(f'Loaded {csv_loaded} category mappings to temp table')

    # Update holdings.manager_type — only where current value is NULL or 'unknown'
    con.execute("""
        UPDATE holdings
        SET manager_type = mc.category
        FROM _manager_categories mc
        WHERE LOWER(TRIM(COALESCE(holdings.inst_parent_name, holdings.manager_name))) = mc.name_clean
          AND (holdings.manager_type IS NULL OR holdings.manager_type = 'unknown')
    """)

    # Also update managers table if it has similar columns
    try:
        con.execute("""
            UPDATE managers
            SET strategy_type = mc.category,
                manager_type = mc.category
            FROM _manager_categories mc
            WHERE LOWER(TRIM(COALESCE(managers.parent_name, managers.manager_name))) = mc.name_clean
              AND (managers.strategy_type IS NULL OR managers.strategy_type = 'unknown')
        """)
        print('Updated managers table')
    except Exception as e:
        print(f'(managers table update skipped: {e})')

    # After snapshot
    after = con.execute("""
        SELECT
            COUNT(CASE WHEN manager_type IS NULL OR manager_type = 'unknown' THEN 1 END) as unknown_rows,
            COUNT(DISTINCT CASE WHEN manager_type IS NULL OR manager_type = 'unknown'
                                THEN COALESCE(inst_parent_name, manager_name) END) as unknown_entities
        FROM holdings
    """).fetchone()
    print(f'AFTER:  unknown rows={after[0]:,}, unknown entities={after[1]:,}')
    print(f'Recovered: {before[1] - after[0]:,} rows, {before[2] - after[1]:,} entities')

    # Distribution of new manager types
    print('\nNew manager_type distribution in holdings:')
    dist = con.execute("""
        SELECT manager_type, COUNT(*) as rows,
               COUNT(DISTINCT COALESCE(inst_parent_name, manager_name)) as entities
        FROM holdings
        GROUP BY manager_type
        ORDER BY rows DESC
    """).fetchdf()
    print(dist.to_string())

    # Spot-check a few
    print('\nSpot-check a few entities:')
    samples = [
        'BATTERY MANAGEMENT CORP.',
        'LILLY ENDOWMENT INC',
        'DEERE & CO',
        'FOUNDRY GROUP, LLC',
    ]
    for s in samples:
        r = con.execute("""
            SELECT COALESCE(inst_parent_name, manager_name) as entity, manager_type
            FROM holdings
            WHERE UPPER(TRIM(COALESCE(inst_parent_name, manager_name))) = ?
            LIMIT 1
        """, [s.upper().strip()]).fetchone()
        if r:
            print(f'  {r[0][:50]:50s} → {r[1]}')
        else:
            print(f'  {s} not found in holdings')

    con.close()
    print('\nDone.')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--production', action='store_true',
                        help='Target production DB (default: staging)')
    args = parser.parse_args()

    base = Path(__file__).parent.parent
    if args.production:
        db = base / 'data' / '13f.duckdb'
        print('WARNING: Running against PRODUCTION database')
    else:
        db = base / 'data' / '13f_staging.duckdb'
        print('Target: staging database')

    if not db.exists():
        print(f'Database not found: {db}')
        sys.exit(1)

    run(str(db))


if __name__ == '__main__':
    main()
